CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "name" varchar(100) NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "role_id" int NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- For the UI Extention one time
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "canvas_sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "title" varchar(150),
  "is_authorized" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "images" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "file_url" text NOT NULL,
  "file_type" varchar(50),
  "file_size" bigint,
  "uploaded_at" timestamp DEFAULT (now())
);

CREATE TABLE "authorized_canvases" (
  "id" uuid PRIMARY KEY,
  "canvas_session_id" uuid UNIQUE NOT NULL,
  "author_name" varchar(100) NOT NULL,
  "title" varchar(150) NOT NULL,
  "authorized_date" date NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "refresh_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT now()
);

ALTER TABLE "refresh_tokens"
ADD CONSTRAINT fk_refresh_user
FOREIGN KEY ("user_id")
REFERENCES "users" ("id")
ON DELETE CASCADE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "canvas_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "images" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "authorized_canvases" ADD FOREIGN KEY ("canvas_session_id") REFERENCES "canvas_sessions" ("id");
